### ISSUE TITLE
Issues Reading Arrow Functions

### ISSUE THREAD

**Issue by luisaugusto** [trivago/prettier-plugin-twig-melody#70] opened 2020-11-28 18:56 UTC
When I use a filter in a Twig template, such as:
```
{{ [1,2,3]|filter(x => x == 1) }}
```

I get the following error:

```
Error: ERROR: Unexpected token "operator" of value ">"
  20 |
  21 | 
> 22 | {{ [1,2,3]|filter(x => x == 1) }}
     |                      ^
  23 | 
    at TokenStream.error (/node_modules/melody-parser/lib/index.js:1362:22)
    at Parser.error (/node_modules/melody-parser/lib/index.js:830:21)
    at Parser.matchPrimaryExpression (/node_modules/melody-parser/lib/index.js:976:26)
    at Parser.getPrimary (/node_modules/melody-parser/lib/index.js:935:21)
    at Parser.matchExpression (/node_modules/melody-parser/lib/index.js:885:25)
    at Parser.matchArguments (/node_modules/melody-parser/lib/index.js:1244:34)
    at Parser.matchFilterExpression (/node_modules/melody-parser/lib/index.js:1214:29)
    at Parser.matchPostfixExpression (/node_modules/melody-parser/lib/index.js:1139:29)
    at Parser.matchPrimaryExpression (/node_modules/melody-parser/lib/index.js:988:21)
    at Parser.getPrimary (/node_modules/melody-parser/lib/index.js:935:21)
```

What should happen is that the Twig parsing should recognize an arrow function and be able to format the file correctly.

**Comment by rubas** [comment] 2021-02-11 13:00
Bump. Same for [`map`](https://twig.symfony.com/doc/2.x/filters/map.html). All arrow functions are not working.

--

@luisaugusto , maybe rename the issue to problems with arrow functions.

**Comment by rubas** [comment] 2021-02-11 13:04
Duplicate of #51.

**Closed** 2022-05-18 17:40 UTC

**Comment by lavandongen** [comment] 2022-11-18 09:28
@luisaugusto you have closed this issue and marked this as completed but the current version still features this issue and hasn't been updated in 3 years. Can we expect an update to the plugin soon? In its current state this plugin isn't useful for more complex projects that use twig to its full extend.
